# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    branches:
      ignore:
        - master
        
    working_directory: ~/Phonograph

    docker:
      - image: circleci/android:api-28

    environment:
      JVM_OPTS: -Xmx2400m

    steps:
      - checkout
      
      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

      - run:
          name: Run Lint
          command: ./gradlew lintRelease
          
      - store_artifacts:
          path: app/build/reports
          destination: reports

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper